import { createPrivateKey, sign as cryptoSign } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Job-lease minting for live-mode probes (P0-1 / THREAT_MODEL B2 / I-04).
 * The fleet rejects heartbeat/complete/cancel without an Ed25519-signed
 * lease whose aud is "cisync-fleet", exp ≤ 60 m and jti binds
 * fleet:<run_id>:<attempt>:<fence_token>. Probes mint credentials with the
 * DEV key generated by `make keys` — production keys never exist here.
 */

const moduleDir = dirname(fileURLToPath(import.meta.url));
const DEV_KEY_PATH = join(moduleDir, '..', '..', '..', 'platform', 'dev-keys', 'joblease_ed25519.dev.key');

export const JOBLEASE_AUDIENCE = 'cisync-fleet';

interface LeaseClaims {
  run_id: string;
  attempt: number;
  fence_token: number;
  repo?: string;
  tier?: number;
  ttl_seconds?: number;
}

function base64url(input: Buffer | string): string {
  return Buffer.from(input).toString('base64url');
}

let cachedKey: ReturnType<typeof createPrivateKey> | undefined;

function devSigningKey(): ReturnType<typeof createPrivateKey> | undefined {
  if (cachedKey !== undefined) return cachedKey;
  try {
    cachedKey = createPrivateKey(readFileSync(DEV_KEY_PATH));
  } catch {
    // Dev key absent (e.g. checkout without `make keys`): probes that need a
    // credential report it instead of forging an invalid token.
    cachedKey = undefined;
  }
  return cachedKey;
}

/** Mint one job-lease token; returns undefined when no dev key is present. */
export function mintJobLeaseToken(claims: LeaseClaims): string | undefined {
  const key = devSigningKey();
  if (!key) return undefined;
  const nowSeconds = Math.floor(Date.now() / 1000);
  const ttl = Math.min(claims.ttl_seconds ?? 1800, 3600);
  const header = base64url(JSON.stringify({ alg: 'EdDSA', typ: 'JWT' }));
  const payload = base64url(
    JSON.stringify({
      aud: JOBLEASE_AUDIENCE,
      jti: `fleet:${claims.run_id}:${claims.attempt}:${claims.fence_token}`,
      run_id: claims.run_id,
      attempt: claims.attempt,
      fence_token: claims.fence_token,
      repo: claims.repo ?? 'acme/probe',
      tier: claims.tier ?? 1,
      iat: nowSeconds,
      exp: nowSeconds + ttl,
    }),
  );
  const signature = cryptoSign(null, Buffer.from(`${header}.${payload}`), key);
  return `${header}.${payload}.${base64url(signature)}`;
}
