#!/usr/bin/env bash
# github-app-manifest.sh — manifest-based GitHub App creation convenience
# (GITHUB_APP_PLAN §1.1 / G14). Emits .env.local fragments with the App
# credentials after the manifest consent flow.
#
# Usage:
#   scripts/github-app-manifest.sh <manifest-json-file>
#
# Flow:
#   1. Print the manifest creation URL (open it, accept the permissions
#      prompt, GitHub shows a one-time `code` in the redirect URL).
#   2. Paste the code; the script exchanges it via
#      POST /app-manifests/{code}/conversions → {id, pem, webhook_secret}.
#   3. Append SAURON_CONN_GITHUB_* fragments to platform/.env.local.
#
# The manifest requests the MINIMAL permission set (plan §1.2): checks RW,
# metadata read, pull requests read, contents read. Deliberately NO
# contents-write / PR-write / workflows / administration.
set -euo pipefail

MANIFEST_FILE="${1:?usage: github-app-manifest.sh <manifest-json-file>}"
ENV_FILE="${ENV_FILE:-platform/.env.local}"

if [[ ! -f "$MANIFEST_FILE" ]]; then
  echo "error: manifest file not found: $MANIFEST_FILE" >&2
  exit 1
fi

require_node() {
  command -v node >/dev/null 2>&1 || {
    echo "error: node is required for JSON parsing (repo toolchain already requires it)" >&2
    exit 1
  }
}
require_node

echo "==> Manifest ready. Open this URL and accept the app creation:"
echo
echo "https://github.com/settings/apps/new?state=unused"
echo
echo "After consent, GitHub redirects to your callback URL with ?code=<one-time-code>."
read -r -p "Paste the one-time code: " CODE

[[ -n "$CODE" ]] || { echo "error: empty code" >&2; exit 1; }

echo "==> Exchanging code for credentials..."
CONVERSION=$(curl -fsS -X POST \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/app-manifests/${CODE}/conversions")

APP_ID=$(node -e 'const r=JSON.parse(require("fs").readFileSync(0,"utf8"));process.stdout.write(String(r.id))' <<<"$CONVERSION")
PEM=$(node -e 'const r=JSON.parse(require("fs").readFileSync(0,"utf8"));process.stdout.write(r.pem||"")' <<<"$CONVERSION")
WEBHOOK_SECRET=$(node -e 'const r=JSON.parse(require("fs").readFileSync(0,"utf8"));process.stdout.write(r.webhook_secret||"")' <<<"$CONVERSION")

[[ -n "$APP_ID" && -n "$PEM" ]] || { echo "error: conversion failed; check the code" >&2; exit 1; }

KEY_DIR="platform/dev-keys"
mkdir -p "$KEY_DIR"
KEY_FILE="${KEY_DIR}/github-app.dev.pem"
umask 177   # WHY: private key material must not be group/world readable
printf '%s' "$PEM" > "$KEY_FILE"
umask 022

read -r -p "Default Installation ID (from the app's install page URL): " INSTALLATION_ID

{
  echo ""
  echo "# --- GitHub App credentials (generated by scripts/github-app-manifest.sh) ---"
  echo "SAURON_CONN_GITHUB_APP_ID=${APP_ID}"
  echo "SAURON_CONN_GITHUB_PRIVATE_KEY_FILE=${KEY_FILE}"
  echo "SAURON_CONN_GITHUB_INSTALLATION_ID=${INSTALLATION_ID:-}"
  echo "SAURON_INGEST_WEBHOOK_SECRETS=${WEBHOOK_SECRET}"
} >> "$ENV_FILE"

echo "==> Wrote credential fragment to ${ENV_FILE}"
echo "    Key written to ${KEY_FILE} (chmod 600). NEVER commit either."
echo "==> Next: subscribe the app to pull_request, push, installation, check_run;"
echo "    set the webhook URL to <tunnel>/hooks/github (compose --profile github)."
